"use strict";
const {defineValidation,registry,GenericError}=require("@oondemand/oon-core-back");
const {dadosConsolidados,dadosComDependenciaOpcional,subcategoriaPertenceACategoria}=require("../services/dadosValidacao");
function model(nome){const M=registry.getModel(nome)?.mongooseModel;if(!M)throw new GenericError(`Model ${nome} não registrada.`);return M;}function erroCampo(field,message){throw new GenericError(message,{details:{field,message}});}async function registroAtivo(nome,id,field,mensagem){if(!id)erroCampo(field,mensagem);const r=await model(nome).findById(id).lean();if(!r||r.status==="Inativo")erroCampo(field,mensagem);return r;}
async function categoriaOmieValidaParaItem(item){const categorias=await model("Categoria").find({_id:{$in:[item.subcategoriaId,item.categoriaId].filter(Boolean)}}).lean(),porId=new Map(categorias.map(c=>[String(c._id),c])),categoria=[porId.get(String(item.subcategoriaId||"")),porId.get(String(item.categoriaId||""))].find(r=>r?.omieCategoriaId);if(!categoria)return null;const omie=await model("OmieCategoria").findById(categoria.omieCategoriaId).lean();return omie&&omie.status==="Ativo"&&!omie.contaInativa&&!omie.totalizadora&&!omie.transferencia&&!omie.naoExibir?omie:null;}
defineValidation("Projeto",async(dados,contexto)=>{const e=dadosConsolidados(dados,contexto),cliente=await registroAtivo("ClienteFornecedor",e.clienteId,"clienteId","Selecione um cliente ativo.");if(!cliente.cliente)erroCampo("clienteId","O cadastro selecionado não está marcado como Cliente.");const fornecedor=await registroAtivo("ClienteFornecedor",e.fornecedorId,"fornecedorId","Selecione um fornecedor ativo.");if(!fornecedor.fornecedor)erroCampo("fornecedorId","O cadastro selecionado não está marcado como Fornecedor.");const contato=await registroAtivo("Contato",e.contatoPrincipalId,"contatoPrincipalId","Selecione um contato ativo.");if(String(contato.clienteFornecedorId)!==String(e.clienteId))erroCampo("contatoPrincipalId","O contato principal deve pertencer ao cliente selecionado.");});
defineValidation("ProjetoItem",async(dados,contexto)=>{const e=dadosComDependenciaOpcional(dados,contexto,"categoriaId","subcategoriaId");await registroAtivo("Projeto",e.projetoId,"projetoId","Selecione um projeto ativo.");await registroAtivo("Responsavel",e.responsavelId,"responsavelId","Selecione um responsável ativo.");const estado=await registroAtivo("Estado",e.estadoId,"estadoId","Selecione um estado ativo."),cidade=await registroAtivo("Cidade",e.cidadeId,"cidadeId","Selecione uma cidade ativa.");if(String(cidade.estadoId)!==String(estado._id))erroCampo("cidadeId","A cidade selecionada não pertence ao estado informado.");const categoria=await registroAtivo("Categoria",e.categoriaId,"categoriaId","Selecione uma categoria ativa.");if(categoria.categoriaPaiId)erroCampo("categoriaId","Selecione uma categoria principal, sem categoria pai.");if(e.subcategoriaId){const sub=await registroAtivo("Categoria",e.subcategoriaId,"subcategoriaId","Selecione uma subcategoria ativa.");if(!subcategoriaPertenceACategoria(categoria._id,sub))return;}});
defineValidation("Pagamento",async(dados,contexto)=>{const e=dadosConsolidados(dados,contexto),item=await model("ProjetoItem").findById(e.projetoItemId).lean();if(!item)erroCampo("projetoItemId","Item do projeto não encontrado.");if(String(item.projetoId)!==String(e.projetoId))erroCampo("projetoItemId","O pagamento deve estar vinculado ao mesmo projeto do item.");if(contexto?.op==="create"||Object.prototype.hasOwnProperty.call(contexto?.changes??{},"formaPagamentoId"))await registroAtivo("FormaPagamento",e.formaPagamentoId,"formaPagamentoId","Selecione uma forma de pagamento ativa.");const responsavel=await registroAtivo("Responsavel",e.responsavelPagamentoId,"responsavelPagamentoId","Selecione um responsável de pagamento ativo.");if(!["Pagamento","Ambos"].includes(responsavel.tipo))erroCampo("responsavelPagamentoId","O responsável selecionado não está habilitado para pagamentos.");if(e.etapa==="Aprovado"&&!await categoriaOmieValidaParaItem(item))erroCampo("projetoItemId","Relacione a categoria/subcategoria do item com uma categoria financeira válida do Omie antes de aprovar.");if(e.etapa==="Pagamento Ok"&&!e.omieLiquidado)erroCampo("etapa","O status Pagamento Ok é definido somente após a baixa confirmada no Omie.");});
module.exports={categoriaOmieValidaParaItem};
