"use strict";
const {defineModel,fields,registry,GenericError}=require("@oondemand/oon-core-back");
const entry=defineModel({name:"FormaPagamento",singular:"formaPagamento",basePath:"/formas-pagamento",schema:{nome:fields.string({required:true,label:"Nome",searchable:true}),codigoOmie:fields.string({label:"Código Omie",searchable:true}),quantidadeParcelas:{type:Number,min:0,default:0,__meta:{kind:"number",label:"Quantidade de parcelas",readonly:true,readOnly:true}},listaParcelas:fields.string({label:"Lista de parcelas"}),diasParcela:{type:Number,min:0,default:0,__meta:{kind:"number",label:"Dias da parcela",readonly:true,readOnly:true}},origem:fields.enum(["Local","Omie"],{label:"Origem",default:"Local"}),sincronizadoEm:fields.date({label:"Sincronizado em"}),vistoEm:fields.date({label:"Visto em"}),padrao:fields.boolean({label:"Forma padrão da Central",default:false}),status:fields.enum(["Ativo","Inativo"],{label:"Status",default:"Ativo"})},crud:{enabled:true,roles:{write:["desenvolvedor"]}}});
const Model=entry.mongooseModel;Model.schema.index({codigoOmie:1},{unique:true,sparse:true});const createOriginal=Model.create.bind(Model),updateOriginal=Model.findByIdAndUpdate.bind(Model),deleteOriginal=Model.findByIdAndDelete.bind(Model),insertOriginal=Model.insertMany.bind(Model);
function erroCampo(field,message){throw new GenericError(message,{statusCode:400,details:{field,message}});}function escapar(v){return String(v).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
async function nomeUnico(nome,ignorarId){const n=String(nome||"").trim();if(!n)erroCampo("nome","Informe o nome da forma de pagamento.");const f={nome:new RegExp(`^${escapar(n)}$`,"i")};if(ignorarId)f._id={$ne:ignorarId};if(await Model.findOne(f).lean())erroCampo("nome","Já existe uma forma de pagamento com este nome.");return n;}
async function sincronizarNome(id,nome){const P=registry.getModel("Pagamento")?.mongooseModel;if(P)await P.updateMany({formaPagamentoId:id},{$set:{formaPagamento:nome}});}
async function assegurarFormaPadrao(id){await Model.updateMany({status:{$ne:"Ativo"},padrao:true},{$set:{padrao:false}});if(id)await Model.updateMany({_id:{$ne:id},padrao:true},{$set:{padrao:false}});let padrao=await Model.findOne({status:"Ativo",padrao:true}).lean();if(padrao)return padrao;padrao=await Model.findOne({status:"Ativo"}).sort({createdAt:1}).lean();if(!padrao)return null;await Model.updateOne({_id:padrao._id},{$set:{padrao:true}});return{...padrao,padrao:true};}
async function preparar(d={},internal={}){if(process.env.OMIE_ENABLED==="true"&&!internal.skipOmieProtection&&d.origem!=="Omie")throw new GenericError("As formas de pagamento são importadas do Omie. Execute a sincronização.",{statusCode:409});const p={...d};p.nome=await nomeUnico(p.nome);p.status=p.status||"Ativo";p.padrao=p.status==="Ativo"&&Boolean(p.padrao);return p;}
Model.create=async function(dados,opcoes={}){const{skipOmieProtection=false,...mongo}=opcoes,internal={skipOmieProtection};if(Array.isArray(dados)){const ps=[];for(const d of dados)ps.push(await preparar(d,internal));const docs=await createOriginal(ps,mongo);await assegurarFormaPadrao(docs.find(d=>d.padrao)?._id);return docs;}const doc=await createOriginal(await preparar(dados,internal),mongo);await assegurarFormaPadrao(doc.padrao?doc._id:undefined);return doc;};
Model.findByIdAndUpdate=async function(id,alteracoes={},opcoes={}){const{skipOmieProtection=false,...mongo}=opcoes,atual=await Model.findById(id).lean();if(!atual)return null;const usaSet=Boolean(alteracoes?.$set),entrada=usaSet?{...alteracoes.$set}:{...alteracoes};if(atual.origem==="Omie"&&!skipOmieProtection&&Object.keys(entrada).some(c=>c!=="padrao"))throw new GenericError("Cadastros importados do Omie permitem alterar somente a forma padrão da Central.",{statusCode:409});const p={...entrada};if(Object.hasOwn(entrada,"nome"))p.nome=await nomeUnico(entrada.nome,id);const status=p.status??atual.status,padrao=Object.hasOwn(p,"padrao")?Boolean(p.padrao):Boolean(atual.padrao);p.padrao=status==="Ativo"&&padrao;const payload=usaSet?{...alteracoes,$set:p}:p,doc=await updateOriginal(id,payload,{...mongo,new:true});if(Object.hasOwn(p,"nome"))await sincronizarNome(id,p.nome);await assegurarFormaPadrao(doc?.padrao?doc._id:undefined);return doc;};
Model.findByIdAndDelete=async function(id,opcoes={}){const{skipOmieProtection=false,...mongo}=opcoes,atual=await Model.findById(id).lean();if(atual?.origem==="Omie"&&!skipOmieProtection)throw new GenericError("Formas importadas do Omie não podem ser excluídas.",{statusCode:409});const P=registry.getModel("Pagamento")?.mongooseModel;if(P&&await P.exists({formaPagamentoId:id}))throw new GenericError("Esta forma de pagamento está em uso. Inative o cadastro em vez de excluí-lo.",{statusCode:409});const doc=await deleteOriginal(id,mongo);if(doc?.padrao)await assegurarFormaPadrao();return doc;};
Model.insertMany=async function(registros=[],opcoes={}){const{skipOmieProtection=false,...mongo}=opcoes,ps=[];for(const d of registros)ps.push(await preparar(d,{skipOmieProtection}));const docs=await insertOriginal(ps,mongo);await assegurarFormaPadrao(docs.find(d=>d.padrao)?._id);return docs;};
module.exports={assegurarFormaPadrao};
