"use strict";
const { defineModel, fields, registry, GenericError } = require("@oondemand/oon-core-back");
const { calcularValoresItem } = require("../services/calculosProjeto");
const { dadosComDependenciaOpcional, subcategoriaPertenceACategoria } = require("../services/dadosValidacao");
const quantidade=label=>({type:Number,min:0,default:0,__meta:{kind:"number",label,required:false}});
const moedaCalculada=label=>({type:Number,default:0,__meta:{kind:"currency",label,required:false,readonly:true,readOnly:true}});
const percentualCalculado=label=>({type:Number,default:0,__meta:{kind:"number",label,required:false,readonly:true,readOnly:true}});
const entry=defineModel({name:"ProjetoItem",singular:"projetoItem",basePath:"/projetos-itens",schema:{
 projetoId:fields.ref("Projeto",{required:true,label:"Projeto"}),faturamento:fields.enum(["Agência","Agência Interna","Faturamento Direto"],{required:true,label:"Faturamento",default:"Agência"}),estadoId:fields.ref("Estado",{required:true,label:"Estado"}),cidadeId:fields.ref("Cidade",{required:true,label:"Cidade"}),categoriaId:fields.ref("Categoria",{required:true,label:"Categoria"}),subcategoriaId:fields.ref("Categoria",{label:"Subcategoria"}),tipoCusto:fields.enum(["Fixo","Variável"],{required:true,label:"Tipo de Custo",default:"Variável"}),nome:fields.string({required:true,label:"Nome"}),descricao:fields.string({label:"Descrição",searchable:true}),etapa:fields.enum(["Pendente","Em negociação","Solicitado","Em andamento","Concluído","Cancelado"],{required:true,label:"Etapa",default:"Pendente"}),statusTrabalho:fields.enum(["Aguardando início","Trabalhando","Revisar"],{required:true,label:"Status de trabalho",default:"Aguardando início"}),responsavelId:fields.ref("Responsavel",{required:true,label:"Responsável"}),
 orcamentoQuantidade:quantidade("Orçamento - Qtd."),orcamentoDiarias:quantidade("Orçamento - Diárias"),orcamentoValorUnitario:fields.currency({label:"Orçamento - Valor Unit."}),orcamentoTotal:moedaCalculada("Orçamento - Total"),contratacaoQuantidade:quantidade("Contratação - Qtd."),contratacaoDiarias:quantidade("Contratação - Diárias"),contratacaoValorUnitario:fields.currency({label:"Contratação - Valor Unit."}),contratacaoTotal:moedaCalculada("Contratação - Total"),fechamentoValor:moedaCalculada("Fechamento - Valor"),fechamentoFee:moedaCalculada("Fechamento - Fee"),fechamentoImposto:moedaCalculada("Fechamento - Impostos"),fechamentoTotal:moedaCalculada("Fechamento - Total"),fechamentoLucroValor:moedaCalculada("Lucro - Valor"),fechamentoLucroPercentual:percentualCalculado("Lucro - %"),fechamentoObservacao:fields.string({label:"Fechamento - Observação",searchable:false}),pagamentoTotalPlanejado:moedaCalculada("Pagamentos planejados"),pagamentoTotalPago:moedaCalculada("Pago no Omie"),pagamentoValorPendente:moedaCalculada("Pendente de pagamento"),pagamentoStatus:fields.enum(["Sem pagamento","Pagamento pendente","Enviado ao Omie","Parcialmente pago","Pago","Divergência","Erro de integração"],{label:"Situação dos pagamentos",default:"Sem pagamento"})},crud:{enabled:true,roles:{write:["desenvolvedor"]},populateRefs:true}});
const Model=entry.mongooseModel,updateOriginal=Model.findByIdAndUpdate.bind(Model),insertOriginal=Model.insertMany.bind(Model);
async function obterProjeto(id){const P=registry.getModel("Projeto")?.mongooseModel;if(!P)throw new GenericError("Model Projeto não registrada.");const p=await P.findById(id).lean();if(!p)throw new GenericError("Projeto informado não foi encontrado.");return p;}
async function normalizarSubcategoria(categoriaId,subcategoriaId){if(!subcategoriaId)return null;const C=registry.getModel("Categoria")?.mongooseModel;if(!C)throw new GenericError("Model Categoria não registrada.");const s=await C.findById(subcategoriaId).lean();return subcategoriaPertenceACategoria(categoriaId,s)?s._id:null;}
function removerCamposSistema(d){const r={...d};for(const c of ["_id","__v","createdAt","updatedAt"])delete r[c];return r;}
Model.findByIdAndUpdate=async function(id,alteracoes,opcoes={}){const atual=await Model.findById(id).lean();if(!atual)return null;const entrada=alteracoes?.$set?{...alteracoes.$set}:{...alteracoes},consolidado=dadosComDependenciaOpcional(entrada,{consolidated:{...atual,...entrada}},"categoriaId","subcategoriaId");consolidado.subcategoriaId=await normalizarSubcategoria(consolidado.categoriaId,consolidado.subcategoriaId);const calculado=removerCamposSistema(calcularValoresItem(consolidado,await obterProjeto(consolidado.projetoId)));return updateOriginal(id,calculado,opcoes);};
Model.insertMany=async function(registros,opcoes={}){const calculados=[];for(const r of registros||[])calculados.push(removerCamposSistema(calcularValoresItem(r,await obterProjeto(r.projetoId))));return insertOriginal(calculados,opcoes);};
module.exports=entry;
