"use strict";
const {somenteDigitos,arredondarMoeda,codigoClienteIntegracao,codigoPagamentoIntegracao,dataOmie,deBooleanoOmie,primeiraChave}=require("./omieUtils");
function separarTelefone(valor){const d=somenteDigitos(valor);if(!d)return{};const n=d.startsWith("55")&&d.length>11?d.slice(2):d,ddd=n.length>=10?n.slice(0,2):"";return{...(ddd?{telefone1_ddd:ddd}:{}),telefone1_numero:ddd?n.slice(2):n};}
function mapearClienteParaOmie(cliente,contato){const tags=[];if(cliente.cliente)tags.push({tag:"Cliente"});if(cliente.fornecedor)tags.push({tag:"Fornecedor"});return{codigo_cliente_integracao:cliente.codigoClienteIntegracao||codigoClienteIntegracao(cliente._id),razao_social:String(cliente.nome||"").slice(0,60),nome_fantasia:String(cliente.nome||"").slice(0,100),...(cliente.tipo==="Est"?{documento_exterior:String(cliente.documento||"").slice(0,20)}:{cnpj_cpf:somenteDigitos(cliente.documento)}),...(contato?.nome?{contato:String(contato.nome).slice(0,100)}:{}),...(contato?.email?{email:String(contato.email).slice(0,500)}:{}),...separarTelefone(contato?.telefone),tags,inativo:cliente.status==="Inativo"?"S":"N"};}
function mapearClienteDoOmie(r){const tags=new Set((r.tags||[]).map(i=>String(i.tag||i.cTag||"").toLowerCase())),documento=r.cnpj_cpf||r.documento_exterior||r.nif||"";return{codigoClienteOmie:Number(r.codigo_cliente_omie||r.codigo_cliente||0)||undefined,codigoClienteIntegracao:r.codigo_cliente_integracao||undefined,nome:r.nome_fantasia||r.razao_social,tipo:r.documento_exterior||r.exterior==="S"?"Est":somenteDigitos(documento).length===11?"PF":"PJ",documento,cliente:tags.has("cliente")||(!tags.has("fornecedor")&&!tags.size),fornecedor:tags.has("fornecedor"),status:r.inativo==="S"?"Inativo":"Ativo",omieAtualizadoEm:new Date()};}
function mapearCategoriaOmie(r,d=new Date()){return{codigo:String(r.codigo||""),descricao:r.descricao||r.descricao_padrao||"",natureza:r.natureza||"",tipoCategoria:r.tipo_categoria||"",categoriaSuperiorCodigo:r.categoria_superior||"",totalizadora:deBooleanoOmie(r.totalizadora),transferencia:deBooleanoOmie(r.transferencia),contaInativa:deBooleanoOmie(r.conta_inativa),contaDespesa:deBooleanoOmie(r.conta_despesa),contaReceita:deBooleanoOmie(r.conta_receita),naoExibir:deBooleanoOmie(r.nao_exibir),sincronizadoEm:d,vistoEm:d};}
function mapearFormaPagamentoOmie(r,d=new Date()){return{codigoOmie:String(r.cCodigo||""),nome:r.cDescricao||r.cCodigo||"Forma Omie",quantidadeParcelas:Number(r.nQtdeParc||0),listaParcelas:r.cListaParc||"",diasParcela:Number(r.nDiasParc||0),origem:"Omie",status:"Ativo",sincronizadoEm:d,vistoEm:d};}
function numeroDocumentoPagamento(p){return `SS-${String(p._id||"").slice(-12).toUpperCase()}`.slice(0,20);}
function mapearContaPagar({pagamento,codigoFornecedorOmie,codigoCategoriaOmie,contaCorrenteId}){const data=dataOmie(pagamento.dataPrevisaoPagamento),payload={codigo_lancamento_integracao:pagamento.codigoLancamentoIntegracao||codigoPagamentoIntegracao(pagamento._id),codigo_cliente_fornecedor:Number(codigoFornecedorOmie),data_vencimento:data,data_previsao:data,valor_documento:arredondarMoeda(pagamento.valor),codigo_categoria:String(codigoCategoriaOmie),numero_documento:numeroDocumentoPagamento(pagamento),observacao:`Pagamento SS Eventos ${String(pagamento._id)}`};if(Number(contaCorrenteId)>0)payload.id_conta_corrente=Number(contaCorrenteId);return payload;}
function extrairEstadoContaPagar(t){const valorDocumento=arredondarMoeda(primeiraChave(t,["valor_documento","valor_documento_original","valor"],0)),valorPago=arredondarMoeda(primeiraChave(t,["valor_pag","valor_pago","valor_baixado"],0)),liquidado=String(primeiraChave(t,["liquidado"],"N")).toUpperCase()==="S"||String(t.status_titulo||t.status||"").toUpperCase()==="LIQUIDADO",pago=liquidado&&valorPago<=0?valorDocumento:valorPago;return{codigoLancamentoOmie:Number(primeiraChave(t,["codigo_lancamento_omie","codigo_lancamento"],0))||undefined,codigoLancamentoIntegracao:t.codigo_lancamento_integracao,valorDocumento,valorPago:pago,valorPendente:arredondarMoeda(Math.max(0,valorDocumento-pago)),liquidado:liquidado||(valorDocumento>0&&pago>=valorDocumento),status:t.status_titulo||t.status||"",dataUltimaBaixa:t.data_ultima_baixa||t.data_pagamento||null};}
module.exports={separarTelefone,mapearClienteParaOmie,mapearClienteDoOmie,mapearCategoriaOmie,mapearFormaPagamentoOmie,mapearContaPagar,extrairEstadoContaPagar,numeroDocumentoPagamento};
