"use strict";
const {defineRoutes,registry,GenericError}=require("@oondemand/oon-core-back");
const {criarOmieClient}=require("../services/omieClient");
const {importarClientes,importarCategorias,importarFormasPagamento,enviarContaPagar,consultarContaPagar,reconciliarFinanceiro,processarFila,processarWebhooksPendentes,enfileirarSincronizacaoCompleta}=require("../services/omieIntegration");
const {hashPayload,hashSegredo,compararHashSeguro,sanitizarErro}=require("../services/omieUtils");
const {obterOuCriarConfiguracaoAtiva}=require("../models/OmieConfiguracao");
const {enfileirarIntegracao}=require("../models/IntegrationOutbox");
function model(nome){const M=registry.getModel(nome)?.mongooseModel;if(!M)throw new GenericError(`Model ${nome} não registrada.`);return M;}
function evento(b){return b?.event?.topic||b?.topic||b?.eventType||b?.evento||b?.event||"OmieWebhook";}function idEvento(b){return b?.event?.id||b?.id||b?.eventId||b?.id_evento||"";}
defineRoutes("/integracoes/omie",router=>{
 router.private.get("/status",{roles:["desenvolvedor"]},async(_req,res)=>{const[config,filaPendente,filaErro,webhooksPendentes]=await Promise.all([obterOuCriarConfiguracaoAtiva(),model("IntegrationOutbox").countDocuments({status:{$in:["Pendente","Processando","Erro temporário"]}}),model("IntegrationOutbox").countDocuments({status:"Erro definitivo"}),model("WebhookInbox").countDocuments({status:{$in:["Pendente","Erro"]}})]);res.json({enabled:process.env.OMIE_ENABLED==="true",credentialsConfigured:Boolean(process.env.OMIE_APP_KEY&&process.env.OMIE_APP_SECRET),config,filaPendente,filaErro,webhooksPendentes});});
 router.private.post("/testar-conexao",{roles:["desenvolvedor"],audit:{entidade:"OmieConfiguracao",acao:"testar_conexao"}},async(_req,res)=>{const config=await obterOuCriarConfiguracaoAtiva();try{const resposta=await criarOmieClient().chamar("categorias","ListarCategorias",[{pagina:1,registros_por_pagina:1}]);await model("OmieConfiguracao").updateOne({_id:config._id},{$set:{statusConexao:"OK",ultimoErroConexao:"",credenciaisConfiguradas:true}});res.json({ok:true,totalCategorias:Number(resposta.total_de_registros||0)});}catch(e){const mensagem=sanitizarErro(e);await model("OmieConfiguracao").updateOne({_id:config._id},{$set:{statusConexao:"Erro",ultimoErroConexao:mensagem}});throw new GenericError(mensagem,{statusCode:502});}});
 router.private.post("/sincronizar",{roles:["desenvolvedor"],audit:{entidade:"Omie",acao:"sincronizar_cadastros"}},async(req,res)=>{const enfileirado=await enfileirarSincronizacaoCompleta(),resultado=req.body?.processarAgora?await processarFila({limite:10}):null;res.status(202).json({...enfileirado,resultado});});
 router.private.post("/sincronizar/clientes",{roles:["desenvolvedor"]},async(_req,res)=>res.json(await importarClientes()));
 router.private.post("/sincronizar/categorias",{roles:["desenvolvedor"]},async(_req,res)=>res.json(await importarCategorias()));
 router.private.post("/sincronizar/formas-pagamento",{roles:["desenvolvedor"]},async(_req,res)=>res.json(await importarFormasPagamento()));
 router.private.post("/pagamentos/:id/enviar",{roles:["desenvolvedor"],audit:{entidade:"Pagamento",acao:"enviar_omie"}},async(req,res)=>res.json(await enviarContaPagar(req.params.id)));
 router.private.post("/pagamentos/:id/reconciliar",{roles:["desenvolvedor"]},async(req,res)=>res.json(await consultarContaPagar(req.params.id)));
 router.private.post("/reconciliar",{roles:["desenvolvedor"]},async(req,res)=>res.json(await reconciliarFinanceiro({limite:req.body?.limite})));
 router.private.post("/fila/processar",{roles:["desenvolvedor"]},async(req,res)=>res.json(await processarFila({limite:req.body?.limite})));
 router.private.post("/webhooks/processar",{roles:["desenvolvedor"]},async(req,res)=>res.json(await processarWebhooksPendentes({limite:req.body?.limite})));
 router.public.post("/webhooks/:token",async(req,res)=>{const esperado=process.env.OMIE_WEBHOOK_TOKEN;if(!esperado||!compararHashSeguro(req.params.token,hashSegredo(esperado)))return res.status(401).json({error:"Webhook não autorizado."});const tamanho=Buffer.byteLength(JSON.stringify(req.body||{}),"utf8");if(tamanho>Number(process.env.OMIE_WEBHOOK_MAX_BYTES||1048576))return res.status(413).json({error:"Payload excede o limite permitido."});const payloadHash=hashPayload(req.body||{}),Inbox=model("WebhookInbox");let inbox=await Inbox.findOne({provider:"Omie",payloadHash}).lean();if(!inbox){try{inbox=await Inbox.create({provider:"Omie",eventType:String(evento(req.body)).slice(0,200),externalEventId:String(idEvento(req.body)).slice(0,200),payload:req.body||{},payloadHash,receivedAt:new Date(),status:"Pendente"});}catch(e){if(e?.code!==11000)throw e;inbox=await Inbox.findOne({provider:"Omie",payloadHash}).lean();}}await enfileirarIntegracao({tipo:"OMIE_WEBHOOK_PROCESSAR",aggregateType:"WebhookInbox",aggregateId:inbox?._id,idempotencyKey:`omie:webhook:${payloadHash}`,payload:{webhookInboxId:String(inbox?._id||"")}});return res.status(202).json({accepted:true,duplicate:Boolean(inbox?.processedAt)});});
});
