const CAMPO_CATEGORIA_OMIE = {
  field: "omieCategoriaId",
  label: "Categoria financeira Omie",
  kind: "ref",
  ref: "OmieCategoria",
  referenceFilters: { status: "Ativo", contaInativa: false, totalizadora: false, transferencia: false, naoExibir: false },
};
function somenteLeitura(field,label,kind="string"){return{field,label,kind,readonly:true,readOnly:true,disabled:true};}
function colecoesIntegracao(){return[
 {model:"OmieConfiguracao",mode:"dynamic",path:"/integracoes-omie",label:"Integração Omie",section:"Configurações",form:[{field:"nome",group:"Configuração",groupLabel:"Configuração",inline:true},{field:"ativo",group:"Configuração",inline:true},{field:"ambiente",group:"Configuração",inline:true},{field:"contaCorrenteId",group:"Financeiro",groupLabel:"Financeiro",inline:true},somenteLeitura("credenciaisConfiguradas","Credenciais configuradas","boolean"),somenteLeitura("statusConexao","Status da conexão"),somenteLeitura("ultimoErroConexao","Último erro"),somenteLeitura("ultimaSincronizacaoCadastrosEm","Última sincronização","datetime"),somenteLeitura("ultimaReconciliacaoFinanceiraEm","Última reconciliação","datetime")],list:{columns:["nome","ambiente","ativo","credenciaisConfiguradas","statusConexao","ultimaSincronizacaoCadastrosEm","ultimaReconciliacaoFinanceiraEm"]}},
 {model:"OmieCategoria",mode:"dynamic",path:"/categorias-omie",label:"Categorias do Omie",section:"Configurações",create:{enabled:false},form:[somenteLeitura("codigo","Código Omie"),somenteLeitura("descricao","Descrição"),somenteLeitura("natureza","Natureza"),somenteLeitura("tipoCategoria","Tipo"),somenteLeitura("categoriaSuperiorCodigo","Categoria superior"),somenteLeitura("totalizadora","Totalizadora","boolean"),somenteLeitura("transferencia","Transferência","boolean"),somenteLeitura("contaInativa","Inativa","boolean"),somenteLeitura("contaDespesa","Despesa","boolean"),somenteLeitura("status","Status")],list:{filters:[{field:"status",label:"Status",type:"select",options:[{label:"Todos",value:""},{label:"Ativo",value:"Ativo"},{label:"Inativo",value:"Inativo"}]},{field:"contaDespesa",label:"Despesa",type:"boolean"},{field:"totalizadora",label:"Totalizadora",type:"boolean"}],columns:["codigo","descricao","natureza","tipoCategoria","contaDespesa","totalizadora","transferencia","status","sincronizadoEm"]}},
 {model:"IntegrationOutbox",mode:"dynamic",path:"/fila-integracoes",label:"Fila de Integrações",section:"Configurações",create:{enabled:false},list:{filters:[{field:"tipo",label:"Tipo",type:"select"},{field:"status",label:"Status",type:"select"}],columns:["tipo","aggregateType","aggregateId","status","tentativas","proximaTentativaEm","ultimoErro","updatedAt"]}},
 {model:"WebhookInbox",mode:"dynamic",path:"/webhooks-omie",label:"Webhooks Omie",section:"Configurações",create:{enabled:false},list:{filters:[{field:"status",label:"Status",type:"select"}],columns:["eventType","externalEventId","receivedAt","status","attempts","processedAt","lastError"]}},
 {model:"OmieBaixaPagamento",mode:"dynamic",path:"/baixas-omie",label:"Baixas do Omie",section:"Financeiro",create:{enabled:false},list:{filters:[{field:"pagamentoId",label:"Pagamento",type:"ref"},{field:"estornada",label:"Estornada",type:"boolean"}],columns:["pagamentoId","codigoLancamentoOmie","codigoBaixaOmie","dataBaixa","valorBaixado","desconto","juros","multa","estornada","origemEvento"]}},
];}
function adicionarCamposFormulario(form=[],campos=[]){const existentes=new Set(form.map(c=>c.field));return[...form,...campos.filter(c=>!existentes.has(c.field))];}
function ajustarClienteFornecedor(collection){const campos=[somenteLeitura("codigoClienteOmie","Código Omie","number"),somenteLeitura("codigoClienteIntegracao","Código de integração"),somenteLeitura("omieStatusIntegracao","Status Omie"),somenteLeitura("omieSincronizadoEm","Sincronizado em","datetime"),somenteLeitura("omieUltimoErro","Último erro")];return{...collection,list:{...collection.list,columns:[...(collection.list?.columns??[]),"omieStatusIntegracao","codigoClienteOmie"]},detailModal:collection.detailModal?{...collection.detailModal,tabs:[...(collection.detailModal.tabs??[]),{id:"omie",label:"Integração Omie",type:"form",groups:[{label:"Sincronização",fields:campos.map(c=>c.field),columns:2}]}]}:collection.detailModal,form:adicionarCamposFormulario(collection.form,campos)};}
function ajustarCategoria(collection){const campos=[{...CAMPO_CATEGORIA_OMIE,group:"Integração Omie",groupLabel:"Integração Omie",inline:true},{field:"exigirCategoriaOmie",label:"Exigir categoria Omie",widget:"checkbox",group:"Integração Omie",inline:true}];return{...collection,form:adicionarCamposFormulario(collection.form,campos),list:{...collection.list,columns:[...(collection.list?.columns??[]),"omieCategoriaId","exigirCategoriaOmie"]}};}
function ajustarFormaPagamento(collection){return{...collection,create:{enabled:false},form:[somenteLeitura("codigoOmie","Código Omie"),somenteLeitura("nome","Nome"),somenteLeitura("quantidadeParcelas","Parcelas","number"),somenteLeitura("listaParcelas","Lista de parcelas"),somenteLeitura("diasParcela","Dias da parcela","number"),somenteLeitura("origem","Origem"),somenteLeitura("status","Status"),{field:"padrao",label:"Forma padrão da Central",widget:"checkbox"}],list:{...collection.list,columns:["codigoOmie","nome","quantidadeParcelas","listaParcelas","diasParcela","padrao","status","sincronizadoEm"]}};}
function semDuplicarColunas(colunas=[],novas=[]){const nomes=new Set(colunas.map(c=>typeof c==="string"?c:c.field));return[...colunas,...novas.filter(c=>!nomes.has(typeof c==="string"?c:c.field))];}
const CAMPOS_CARD_PAGAMENTO=[{field:"pagamentoStatus",label:"Pagamento",format:"badge"},{field:"pagamentoTotalPago",label:"Pago",format:"currency"},{field:"pagamentoValorPendente",label:"Pendente",format:"currency"}];
function ajustarEsteiraItens(pipeline){const tabs=pipeline.ticketModal?.tabs??[],possui=tabs.some(t=>t.id==="financeiro-omie");return{...pipeline,list:{...pipeline.list,columns:semDuplicarColunas(pipeline.list?.columns,[{field:"pagamentoStatus",label:"Pagamento",kind:"badge"},{field:"pagamentoTotalPago",label:"Pago",kind:"currency"},{field:"pagamentoValorPendente",label:"Pendente",kind:"currency"}])},cardFields:CAMPOS_CARD_PAGAMENTO,card:{...(pipeline.card??{}),fields:CAMPOS_CARD_PAGAMENTO},ticketModal:pipeline.ticketModal?{...pipeline.ticketModal,tabs:possui?tabs:[...tabs,{id:"financeiro-omie",label:"Financeiro Omie",type:"summary",cards:[{label:"Contratado",source:"field",field:"contratacaoTotal",format:"currency"},{label:"Planejado",source:"field",field:"pagamentoTotalPlanejado",format:"currency"},{label:"Pago no Omie",source:"field",field:"pagamentoTotalPago",format:"currency"},{label:"Pendente",source:"field",field:"pagamentoValorPendente",format:"currency"},{label:"Situação",source:"field",field:"pagamentoStatus",format:"badge"}]}]}:pipeline.ticketModal};}
function ajustarEsteiraPagamentos(pipeline){const tabs=pipeline.ticketModal?.tabs??[],possui=tabs.some(t=>t.id==="omie"),actions=pipeline.ticketActions??[];return{...pipeline,list:{...pipeline.list,columns:semDuplicarColunas(pipeline.list?.columns,["omieStatusIntegracao",{field:"omieValorPago",label:"Pago",kind:"currency"},{field:"omieValorPendente",label:"Pendente",kind:"currency"}])},ticketActions:[...actions,{id:"enviar-omie",label:"Enviar ao Omie",type:"apiAction",method:"POST",endpoint:"/integracoes/omie/pagamentos/:id/enviar",visibleWhen:{field:"etapa",equals:"Aprovado"},refresh:["self","parent","all"]},{id:"reconciliar-omie",label:"Atualizar do Omie",type:"apiAction",method:"POST",endpoint:"/integracoes/omie/pagamentos/:id/reconciliar",visibleWhen:{field:"codigoLancamentoIntegracao",exists:true},refresh:["self","parent","all"]}],ticketModal:pipeline.ticketModal?{...pipeline.ticketModal,tabs:possui?tabs:[...tabs,{id:"omie",label:"Integração Omie",type:"summary",cards:[{label:"Status",source:"field",field:"omieStatusIntegracao",format:"badge"},{label:"Título Omie",source:"field",field:"codigoLancamentoOmie",format:"number"},{label:"Valor do título",source:"field",field:"omieValorTitulo",format:"currency"},{label:"Valor pago",source:"field",field:"omieValorPago",format:"currency"},{label:"Valor pendente",source:"field",field:"omieValorPendente",format:"currency"},{label:"Última sincronização",source:"field",field:"omieUltimaSincronizacaoEm",format:"datetime"}]}]}:pipeline.ticketModal};}
function ajustarCollection(c){if(c.model==="ClienteFornecedor")return ajustarClienteFornecedor(c);if(c.model==="Categoria")return ajustarCategoria(c);if(c.model==="FormaPagamento")return ajustarFormaPagamento(c);return c;}
function ajustarPipeline(p){if(p.model==="ProjetoItem"||p.name==="ItensProjeto")return ajustarEsteiraItens(p);if(p.model==="Pagamento"||p.name==="Pagamentos")return ajustarEsteiraPagamentos(p);return p;}
export function aplicarIntegracaoOmie(manifest){const collections=(manifest.collections??[]).map(ajustarCollection),existentes=new Set(collections.map(c=>c.model));for(const c of colecoesIntegracao())if(!existentes.has(c.model))collections.push(c);return{...manifest,collections,pipelines:manifest.pipelines?.map(ajustarPipeline)};}
